name: Build and Release
#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
on:
  push:
    tags:
      - '*'  # 当有标签推送时触发

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest,macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install --force

      - name: Build
        run: |
          wails build



      - name: Ls1
        if: matrix.os == 'macos-latest'
        run: |
          cd 'build/bin/'
          ls

      - name: Ls2
        if: matrix.os == 'windows-latest'
        run: |
          cd 'build/bin/'
          dir

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-files
          path: |
            build/bin/*

  release:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: compiled-files
          path: downloaded-assets

      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_TEST_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            downloaded-assets/*

