name: Fine Auto Release
on:
  push:
    tags:
      - '*'  # 当有标签推送时触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'


      - name: Build WxMiniProgramDecompile
        run: |
          Invoke-WebRequest -Uri 'https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip' -OutFile 'upx.zip'
          Expand-Archive -Path 'upx.zip' -DestinationPath 'upx' -Force
          cd wechatMiniProgram
          npm install pkg
          npm install --force
          npm run build
          cd ../backend/service/service/wechat && mv decompile.exe decompile


      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install --force

      - name: Build
        run: |
          wails build
          upx/upx-4.2.2-win64/upx.exe build/bin/Fine.exe -9

      - name: Zip Build Artifacts
        run: |
          cd build/bin/
          Compress-Archive -Path .\* -DestinationPath .\Fine-amd64.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifact
          path: |
            build/bin/Fine-amd64.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build WxMiniProgramDecompile
        run: |
          wget https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-src.tar.xz
          tar -zxvf upx-4.2.2-src.tar.xz
          cd upx-4.2.2-src
          make
          cd ../wechatMiniProgram
          npm install pkg
          npm install --force
          npm run build

      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install --force

      - name: Build
        run: |
          wails build
#          macos upx无法压缩

      - name: Zip Build Artifacts
        run: |
          cd build/bin/
          zip -r Fine-darwin.zip *

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifact
          path: |
            build/bin/Fine-darwin.zip
  release:
    runs-on: macos-latest
    needs: [build-macos,build-windows]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-artifact
          path: artifacts/

      - name: Download Macos Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: macos-artifact
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/*
          body: |
            1. 修复Quake翻页BUG。
            

        env:
         GITHUB_TOKEN: ${{ secrets.FINE_ACCESS_TOKEN }}
#         GITHUB_TOKEN: ${{ secrets.FINE_TEST_ACCESS_TOKEN }}