name: Fine release

on:
  push:
    tags:
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
#  NODE_OPTIONS: "--max-old-space-size=4096"
  go-version: '1.24.0'
  node-version: '18'
  wails-version: 'latest'

jobs:
  build:
    strategy:
      # true: 一个失败全终止
      fail-fast: true
      matrix:
        build:
          - os: "windows"
            arch: 'amd64'
            runs-on: 'windows-latest'
          - os: "darwin"
            arch: 'amd64'
            runs-on: 'macos-13'
          - os: "darwin"
            arch: 'arm64'
            runs-on: 'macos-latest'

    runs-on: ${{ matrix.build.runs-on }}
    env:
      CGO_ENABLED: 1
      GOOS: ${{ matrix.build.os }}
      GOARCH: ${{ matrix.build.arch }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set artifact name
        id: set_artifact_name
        run: |
          echo "artifact_name=${{ format('Fine_{0}_{1}{2}', matrix.build.os, matrix.build.arch, matrix.build.os == 'windows' && '.exe' || '.app') }}"
          echo "::set-output name=artifact_name::${{ format('Fine_{0}_{1}{2}', matrix.build.os, matrix.build.arch, matrix.build.os == 'windows' && '.exe' || '.app') }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@${{ env.wails-version }}

      - name: Install UPX
        if: matrix.build.os == 'windows'
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Build artifact
        run: |
          wails build --platform ${{ matrix.build.os }}/${{ matrix.build.arch }} -o ${{ steps.set_artifact_name.outputs.artifact_name }}

      - name: Compress artifact
        if: matrix.build.os != 'darwin'
        run: |
          upx build/bin/* -9

      - name: Zip mac artifact
        if: matrix.build.os == 'darwin'
        run: |
          ditto -c -k --keepParent build/bin/Fine.app build/bin/${{ steps.set_artifact_name.outputs.artifact_name }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.artifact_name }}${{ matrix.build.os == 'darwin' && '.zip' || '' }}
          path: build/bin/${{ steps.set_artifact_name.outputs.artifact_name }}${{ matrix.build.os == 'darwin' && '.zip' || '' }}

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/artifacts

      - name: List artifacts
        run: |
          ls -al artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/**
          token: ${{ secrets.FINE }}
          body: |
            feature: Shodan @zhifana #2;
            feature: macOS微信小程序自定义路径 @allinu #18;
            feature: ICP任务删除 @littleheary #24, @xiaoliusec #25;
            enhance: 小程序反编译日志过多；
            enhance: 小程序反编译改为Go;
            enhance: 小程序敏感信息提取正则;
            enhance: ICP任务暂停;
            fix: httpx结果抖动;
            fix: 清除Applet文件夹无法清除当前列表;
            fix: 小程序重新设置路径后不会马上生效。
            
            
            


